### PR TITLE
adding jquery chosen plugin internally to not use shared libs

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This should resolve issue with breaking changes in 5.1.0, cc @sbesson

### CODE REVIEW

**Comment by pwalczysko** [comment]
On trout merge a bug on webtagging (specific for trout merge => not on trout latest, not on octopus latest): 
  - select a dataset, go to Auto Tag in central pane
  - select the "New Existing Tag" in one column
  - click okay, the ticks in the boxes in the central panel appear as expected
  - click Apply now - the column goes green as epxected
  - click "New Existing Tag" on another column
  - click okay, the ticks appear again as expected BUT
  - the "Apply" button is disabled -> not expected

**Comment by pwalczysko** [comment]
Repeating this on trout latest as well. https://github.com/dpwrussell/webtagging/pull/20#issuecomment-83596192

**Comment by pwalczysko** [comment]
Trout merge specific bug (not on trout latest) in Tag Search : When selecting two tags to search for, spinner spins forever, cannot load the right hand pane

screen shot 2015-03-18 at 12 00 13

**Comment by aleksandra-tarkowska** [comment]
@pwalczysko @sbesson that should resolve all issues

**Comment by aleksandra-tarkowska** [comment]
There is still "GET /static/3rdparty/jquery.tooltip/jquery.tooltip.pack.js HTTP/1.1" 404 1742 broken although this file doesn't exist (the same on latest)

**Comment by aleksandra-tarkowska** [comment]
I moved enableing button above js code, as for some reason updating jstree is failing,
```
Error: Syntax error, unrecognized expression: li:[id^='image']
```
I don't have time to investigate that now, although moving button above that code resolve the issue.

**Comment by pwalczysko** [comment]
Webtagging workflows work as expected now on trout merge, including Apply button, and Tag Search.

**Comment by aleksandra-tarkowska** [comment]
The plugin has another bugs, like when you uncheck all checkboxes in a column and save is not removing it.

**Comment by dpwrussell** [comment]
@aleksandra-tarkowska Is that latest issue also a new issue?

**Comment by aleksandra-tarkowska** [comment]
@dpwrussell that is an existing issue. We also figured out that when you uncheck (remove tags) then click refresh they will be blue again. Then when you Apply, these blue will be counted as chosen, even you unchecked them before refreshing. If you do not see table on the full screen you can end up with unwanted tags.

**Comment by pwalczysko** [comment]
@dpwrussell : I think the problems notified here by @aleksandra-tarkowska are coming from the fact that the "Refresh" button does not refresh, but instaed is "going to the default state".  Couple of alternate clicks on Refresh and Apply with ticking and unticking boxes in between can bring you to a state where you do not know anymore... - what is the purpose of the Refresh button and its naming @dpwrussell ? I suppose you might have users which are fixed to this behaviour, but it seems pretty confusing.

**Comment by dpwrussell** [comment]
@pwalczysko Ok, thanks, I get the idea, I'll have a look.

**Comment by aleksandra-tarkowska** [comment]
@dpwrussell as https://github.com/openmicroscopy/openmicroscopy/pull/3629 is in could you please merge that as well?

**Comment by pwalczysko** [comment]
Please note that with this, we have webtagging working on 5.1 (trout merge and latest)j. Nevertheless, the features are broken with this webtagging PR on 5.0 line (octopus). On the positive side, we checked that the previous, released webtagging version does work on 5.0. Which means all what is missing is backward compatilbility of this vs. 5.0. Atm we are inclined to simply explain this limitation and go ahead. I would recommend to merge this PR.

**Comment by dpwrussell** [comment]
@aleksandra-tarkowska Just reviewed your changes and they look good

One question though, the links to jquery-ui, tablesorter and jquery.form have all been updated to point to their new specific versions in webclient, but chosen has been embedded instead of having an updated link. Any particular reason for not also just updating that link as well?

Thanks.

**Comment by aleksandra-tarkowska** [comment]
We wasn't sure if it will work with new version 1.2.0. You may not noticed but the breaking changes when upgrading jquary, ui, etc and chosen broke WebAdmin. We decided to go for the old one.

**Comment by dpwrussell** [comment]
Ok, this looks good. Merging, thanks.

**Pull request merged**
